name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - cached-property=1.5.2
  - cachetools=5.0.0
  - certifi
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - executing=0.8.3
  - flatbuffers=2.0
  - frozenlist=1.2.0
  - gast=0.5.3
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=3.6.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython-genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter-client=7.1.2
  - jupyter-console=6.4.0
  - jupyter-core=4.9.2
  - jupyterlab-pygments=0.1.2
  - jupyterlab-widgets=1.0.0
  - keras=2.8.0
  - kiwisolver=1.3.2
  - libffi=3.3
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libstdcxx-ng
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - nbclient=0.5.11
  - nbconvert=6.4.4
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numpy=1.22.3
  - oauthlib=3.2.0
  - opt-einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip
  - prometheus-client=0.13.1
  - prompt-toolkit=3.0.20
  - protobuf=3.19.4
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure-eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qtconsole=5.2.2
  - qtpy=2.0.1
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.0
  - stack-data=0.2.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.8.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.12
  - pip:
      - en-core-web-sm==3.2.0
      - regex==2022.3.15
      - spacy==3.2.2
      - srsly==2.4.2
      - thinc==8.0.13
      - wasabi==0.9.0
